### ISSUE TITLE
Missing bundle.min.js and bundle.min.css in design adminhtml.

### ISSUE THREAD

**Issue by Sarvesh-A** [jetrails/magento-cloudflare#110]
Hello,

I installed this Cloudflare module in my local as we want to use Cloudflare services from Magento1 backend. After installing I noticed there are two libraries missing in admin bundle.min.js and bundle.min.css so page seems to be broken. I've attached a screenshot for better understanding.

Please send us both files of Magento1 or please let us know where we can download the full module.

Help would be appreciated.

Thanks.

![Screenshot_from_2020_07_08_19_00_45](https://user-images.githubusercontent.com/33909592/86911204-810d5a80-c14d-11ea-86cb-e07127eb60cf.png)

**Comment by null93** [comment]
I would be glad to help you out. My guess is that you installed the module using the contents of the `src` folder. These files do not include the bundled CSS & JS. Take a look at the [Releases Page](https://github.com/jetrails/magento-cloudflare/releases) and download the asset named [JetRails_Cloudflare-1.1.7.tgz](https://github.com/jetrails/magento-cloudflare/releases/download/1.1.7/JetRails_Cloudflare-1.1.7.tgz). 

Try to reinstall and let me know how it goes. Please remember to follow the directions that are outlined in the documentation:
https://learn.jetrails.com/article/magento-1-cloudflare-extension

**Comment by null93** [comment]
I will be closing this issue, reopen if needed.

**Comment by Sarvesh-A** [comment]
Hello @null93 

Thanks for your help. It's working well as expected. :)
